lentics/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('processing.views',
    url(r'^$', 'home', name='home'),
    # Users admin
    url(r'^register/$', 'register_user'),
    url(r'^login/$', 'log_in'),
    url(r'^login/auth/$', 'auth_view'),
    url(r'^logout/$', 'log_out'),
    # Files admin
    url(r'^files/$', 'show_files'),
    url(r'^files/upload/$', 'show_fileupload', name='file_upload'),
    url(r'^files/submit/$', 'filesubmit'),
    #url(r'^files/success/$', 'upload_success', name='upload_success'),
    url(r'^files/delete/(\d+)/$', 'delete_file'),
    url(r'^files/edit/(\d+)/$', 'show_edit_file', name='show_edit_file'),
    url(r'^files/(?P<id_file>\d+)/$', 'download_file', name="download_file"),
    # Proccesses admin
    url(r'^process/show/(?P<process_id>\d+)/$', 'show_specific_process', name="show_specific_process"),
    url(r'^process/error/(?P<process_id>\d+)/$', 'show_error_process', name="show_error_process"),
    url(r'^process/show/$', 'show_process', name='show_process'),
    url(r'^process/$', 'show_processes'), #revisar
    url(r'^editfile/$', 'editfile'),
    # Tools execution
    url(r'^processing/$', 'processing'),
    #HELP
    url(r'^help/video/$', 'show_video'),
    url(r'^help/tutorial/$', 'show_tutorial'),
    # Admin admin
    url(r'^admin/', include(admin.site.urls)),
)

processing/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django import forms
import subprocess
import datetime
import threading
from django.conf import settings
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.models import User
from time import sleep
from django.core.files import File as Django_File
from django.conf import settings
from random import randint
import os
import csv
import ast
#from image_cropping import ImageCropWidget
#from image_cropping import ImageCropField, ImageRatioField

# Opciones estáticas
POSIBLES_ESTADOS_PROCESOS = (
    (0, "Terminado exitosamente"),
    (1, "Terminado con errores"),
    (2, "Ejecutandose"),
    (3, "En espera")
)
TIPO = (
    (0, "output"),
    (1, "input"),
)
FORMATO = (
    (0, "tif"),
    (1, "tiff"),
)

class Profile(models.Model):
    user = models.OneToOneField(User)
    email = models.EmailField()
    firstName = models.CharField(max_length=30)
    lastName = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = 'Perfiles'

    def __unicode__(self):
        return unicode(self.email)


class File(models.Model):
    fileUpload = models.FileField()
    #pan_image = ImageCropField(blank=True, upload_to='uploaded_images')
    # size is "width x height"
    #cropping = ImageRatioField('pan_image', '430x360')
    x = models.IntegerField(default=0)
    y = models.IntegerField(default=0)
    cell_size = models.IntegerField(default=1)
    description = models.TextField(default="")
    profile = models.ForeignKey(Profile)
    ext = models.CharField(max_length=7)
    tipo = models.IntegerField(choices=TIPO, default=0)
    test = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Archivos'

    def get_contenido(self):
        # falta/pendiente cambiar direccion
        return Django_File(open("%s%s" % (settings.BASE_DIR, self.fileUpload.url))).read()

    def get_kmer_dict(self):
        with open("%s%s" % (settings.BASE_DIR, self.fileUpload.url)) as file_object:
            d = list(csv.reader(file_object, delimiter="\t", dialect=csv.excel))
        return sorted(d)

    def __unicode__(self):
        return u"Imagen\nDescription: %s " % (self.description)


#class ImagesForm(forms.ModelForm):
#    class Meta:
#        model = File
#        fields = ('pan_image',)


class Proceso(models.Model):

    estado = models.IntegerField(choices=POSIBLES_ESTADOS_PROCESOS, default=3)
    std_err = models.TextField(default="None")
    std_out = models.TextField(default="None")
    comando = models.CharField(max_length=2000, default="echo Hola mundo")
    profile = models.ForeignKey(Profile)
    inicio = models.DateTimeField(auto_now_add=True)
    fin = models.DateTimeField(null=True)
    resultado = models.ForeignKey(File, null=True, blank=True)
    shapes = models.TextField(default="None")
    images = models.TextField(default="None")

    class Meta:
        verbose_name_plural = 'Procesos'

    def get_estado(self):
        return POSIBLES_ESTADOS_PROCESOS[self.estado][1] if self.estado <= 3 else "Terminado con errores"

    def get_resultado(self):
        return self.resultado.get_contenido()

    def get_kmer_dict(self):
        if "Tallymer" == self.contador:
            return sorted(self.resultado.get_kmer_dict(), key=lambda x: x[1])
        else:
            return self.resultado.get_kmer_dict()

    def run_process(self):
        self.estado = 2
        self.save()
        try:
            p = subprocess.Popen(
                str(self.comando), stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
            self.std_out, self.std_err = p.communicate()
            self.estado = p.returncode
            print p.returncode
            self.fin = datetime.datetime.now()
        except:
            try:
                self.std_out, self.std_err = p.communicate()
                self.estado = 0
                self.save()
                self.fin = datetime.datetime.now()
            except:
                self.estado = 0
                self.save()
                self.fin = datetime.datetime.now()
        #  self.std_out = self.std_out.replace("\n", "<br>")
        #  self.std_err = self.std_err.replace("\n", "<br>")
        self.save()

    def run(self):
        t = threading.Thread(target=self.run_process)
        t.setDaemon(True)
        t.start()

    def __unicode__(self):
        return u"ID: %s Estado: %s \n Comando: %s \n" % (str(self.id), str(self.estado), str(self.comando))


class Fusion(models.Model):

    name = models.TextField(default="Lentic area calculation")
    procesos = models.ManyToManyField(Proceso)
    profile = models.ForeignKey(Profile)
    out_files = models.TextField(default="None")
    nivel = models.IntegerField(default=1)

    def run_this(self, file_list=""):
        self.name = "Lentic #%s" % self.id
        self.save()
        # lista de archivos temporales
        temp_list = []
        img_list = []
        # Se ejecuta el Scrip creado para fusionar las imagenes
        comando = ""
        for img in file_list:
            tmp_dir = "lentic_%s.tif" % randint(1, 1000000)
            temp_list.append(tmp_dir)
            img_list.append(img)
            comando = comando +"python /home/nazkter/Sofware_Develop/lentic/bin/lentico.py /home/nazkter/Sofware_Develop/lentic/files/%s /home/nazkter/Sofware_Develop/lentic/files/output/%s && " % (img, tmp_dir)
        comando = comando[0:-3]
        print "comando: %s" % (comando)
        print temp_list
        # Se crea el proseso y se envia a la cola
        p1 = Proceso(comando=str(comando),profile=self.profile)
        p1.save()
        self.procesos.add(p1)
        # To get files with path: tales.fileUpload.path
        # Se genera indice y espero hasta que este listo
        t1 = threading.Thread(target=p1.run_process)
        t1.setDaemon(True)
        t1.start()
        while t1.isAlive():
            sleep(1)
        #file_name = "/tmp/%s.shp" % tmp_dir
        #with open(file_name, 'r+') as f:
        #    text = f.read()
        #    f.seek(0)
        #    f.truncate()
        #    f.write(text.replace(' ', '\t'))
        
        #out_files = File(fileUpload=Django_File(open(
        #    file_name)), description="Salida " + self.name, profile=self.profile, ext="results")
        #out_file.save()'''
        self.out_files = str(temp_list)
        p1.shapes = str(temp_list)
        p1.images = str(img_list)
        p1.save()

    def run(self, file_list=""):
        t = threading.Thread(target=self.run_this, kwargs=dict(
            file_list=file_list))
        t.setDaemon(True)
        t.start()

    class Meta:
        verbose_name_plural = "Procesos de alinear y estimar abundancia"

    def __unicode__(self):
        return u"Alineamiento y estimación \n %s" % self.name

processing/forms.py
from django import forms
from django.db import models


class UploadFileForm(forms.Form): 
    title = forms.CharField(max_length=50) 
    fileUploaded = forms.FileField() 
    description = models.TextField(max_length=200)

lentics/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <!-- Optional theme -->  
    <title>{% block title %}Lentic Water Bodies Comparison (LWBC){% endblock %}</title>
        <!-- Latest compiled and minified JavaScript and JQuery-->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.Jcrop.min.js' %}"></script>
    <script src="{% static 'js/plotly.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/jquery.Jcrop.min.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/LWBC.css' %}" type="text/css" />
</head>
<body>
<div class="container" style="width: 100%!important;">
    <div class="row">
        <div class="col-sm-12">
        <nav class="navbar navbar-default" role="navigation">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <a class="navbar-brand" href="/">Lentic Water Bodies Comparison (LWBC)</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                {% if not user.is_authenticated %}
                    <li>
                    <a href="/register/">Registrarse</a>
                    </li>
                    <li><a href="/login/">Acceder</a></li>
                {% else %}
                <span></span>
                    <li  class="active" ><a href="#" style="cursor:default">Bienvenido, {{user.profile.firstName}}</a>  </li>
                    <li role="separator" class="divider"></li>
                    <li><a href="/logout/">Salir</a></li>
                {% endif %}
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
        </div>
    </div>
    <div class="row">
        {% if user.is_authenticated %}
        <div class="col-sm-2">
            <ul class="nav nav-pills nav-stacked">
                <li ><a href="/">Home</a></li>
                <li ><a href="/files/">Imagenes</a></li>
                <li ><a href="/process/show/">Procesos</a></li>
            </ul>
            <div class="alert alert-success" style="bottom: 30px;position: fixed;">
                <strong>Ayuda: </strong><br><br>
                &#8226; <a href="/help/video/">Video </a><br>
                &#8226; <a href="/help/tutorial/" target="_blank">Tutorial </a>
            </div>
            <!-- <div id="preview-pane" style="position: fixed;z-index: 2000;bottom: 5px;left: 5px;">
                <div class="preview-container">
                    <img src="{% static 'default.png' %}" class="jcrop-preview" id="preview_mul" alt="Preview" />
                </div>
            </div> -->
        </div>
        {% endif %}
        {% if user.is_authenticated %}
        <div class="col-sm-10" style="border-left: solid rgb(80, 121, 150) 1px;">
        {% endif %}
            {% block content %}{% endblock %}
        {% if user.is_authenticated %}
        </div>
        {% endif %}
    </div>        
</div>
<script type="text/javascript">
// se declara la API de jcrop para interactuar con la imagen 
var jcrop_api

/* Grab some information about the preview pane
$preview = $('#preview-pane'),
$pcnt = $('#preview-pane .preview-container'),
$pimg = $('#preview-pane .preview-container img'),

xsize = $pcnt.width(),
ysize = $pcnt.height();*/

$('#id_file').on('change', function (e) {
    /*$("#id_tam_pixel_mul").val(json[this.value].cell_size);
    $("#id_lat_mul").val(json[this.value].x);
    $("#id_lon_mul").val(json[this.value].y);*/
    // si ya existe un API declarado, lo destruyo para poder redimencionar la imagen
    if(jcrop_api) jcrop_api.destroy();
    $('#target_mul').attr('src',/static/+this.value+'.jpg');
    $('#target_mul').attr('style','max-width: 100%');  
});
$(document).on('input', '#id_diadica_mul', function() {
    //se actualiza el valor en frontend
    var diadic_val = $('#id_diadica_mul').val();
    $('#id_diadica_mul_val').html( diadic_val );
    //se cambia el tamaño del recorte
    var max_val_diadic = Math.pow(2, diadic_val);
    if(jcrop_api) jcrop_api.setSelect([0, 0, max_val_diadic, max_val_diadic]);
});

$('#id_btn_cortar').on('click', function (e) {
// verifico que los campos esten llenos
if(!verificarCampos()){
    alert('debe llenar todos los campos');
}else{
        
    var image = new Image();
    image.src = $('#target_pan').attr("src");
    if (image.naturalHeight == 0) image.src = $('#target_mul').attr("src");
    //creo un nuevo widget de Jcrop para la nueva imagen
    $('#target_pan').Jcrop({
        //onChange: showPreview_pan,
        trueSize: [image.naturalWidth,image.naturalHeight],
        bgColor:     'black',
        bgOpacity:   .2,
        setSelect:   [ 0, 0, 0, 0 ],
        aspectRatio: 1,
        allowResize: false,
        allowSelect: false
    },function(){
        jcrop_api_pan = this;
    });
    //Establesco los valores del slider que determina el tamaño del recorte
    var image = new Image();
    image.src = $('#target_mul').attr("src");
    if (image.naturalHeight == 0) image.src = $('#target_mul').attr("src");
    //creo un nuevo widget de Jcrop para la nueva imagen
    $('#target_mul').Jcrop({
        onChange: move_jcrops,
        trueSize: [image.naturalWidth,image.naturalHeight],
        bgColor:     'black',
        bgOpacity:   .2,
        setSelect:   [ 0, 0, 200, 200 ],
        aspectRatio: 1,
        allowResize: true,
        allowSelect: true
    },function(){
        // Use the API to get the real image size
        //var bounds = this.getBounds();
        //boundx = bounds[0];
        //boundy = bounds[1];
        // Store the API in the jcrop_api variable
        jcrop_api = this;
        // Move the preview into the jcrop container for css positioning
        //$preview.appendTo(jcrop_api_mul.ui.holder);
        
    });
}
});
function verificarCampos(){
    return true
    if(
        $('#id_tam_pixel_mul').val().trim() === '' ||
        $('#id_lon_mul').val().trim() === '' ||
        $('#id_lat_mul').val().trim() === ''
         ){
        return false
    }else{return true}
}
function move_jcrops(c){
    $('#id_x_mul').val(c.x)
    $('#id_y_mul').val(c.y)
    $('#id_x2_mul').val(c.x2)
    $('#id_y2_mul').val(c.y2)
/*
    if (parseInt(c.w) > 0)
      {
        proporcion = $('#id_tam_pixel_mul').val() / $('#id_tam_pixel_pan').val();
        desfaseX = ($('#id_lon_mul').val() - $('#id_lon_pan').val())*proporcion;
        desfaseY = ($('#id_lat_mul').val() - $('#id_lat_pan').val())*proporcion;

        x1= c.x - desfaseX
        console.log('x1:'+c.x+' -'+desfaseX)
        y1= c.y - desfaseY
        x2= c.x2 - desfaseX
        y2= c.y2 - desfaseY
        $('#id_x_mul').val(c.x)
        $('#id_y_mul').val(c.y)
        $('#id_x2_mul').val(c.x2)
        $('#id_y2_mul').val(c.y2)
        $('#id_x_pan').val(x1*proporcion)
        $('#id_y_pan').val(y1*proporcion)
        $('#id_x2_pan').val(x2*proporcion)
        $('#id_y2_pan').val(y2*proporcion)
        console.log('desfase en x: '+desfaseX);
        console.log('desfase en y: '+desfaseY);
        if(jcrop_api) jcrop_api.setSelect([x1*proporcion, y1*proporcion, x2*proporcion, y2*proporcion]);

      }*/
}
// function showPreview_pan(coords){
//     var rx = 100 / coords.w;
//     var ry = 100 / coords.h;
//     $('#preview_pan').css({
//         width: Math.round(rx * $('target_mul').width()) + 'px',
//         height: Math.round(ry * $('target_mul').height()) + 'px',
//         marginLeft: '-' + Math.round(rx * coords.x) + 'px',
//         marginTop: '-' + Math.round(ry * coords.y) + 'px'
//     });
// }
</script>
<style type="text/css">

/* Apply these styles only when #preview-pane has
   been placed within the Jcrop widget */
.jcrop-holder #preview-pane {
    display: block;
    position: fixed;
    z-index: 2000;
    bottom: 5px;
    left: 5px;
    padding: 1px;
    border: 1px rgba(0,0,0,.4) solid;
    background-color: white;

    -webkit-border-radius: 6px;
    -moz-border-radius: 6px;
    border-radius: 6px;

    -webkit-box-shadow: 1px 1px 5px 2px rgba(0, 0, 0, 0.2);
    -moz-box-shadow: 1px 1px 5px 2px rgba(0, 0, 0, 0.2);
    box-shadow: 1px 1px 5px 2px rgba(0, 0, 0, 0.2);
}

/* The Javascript code will set the aspect ratio of the crop
   area based on the size of the thumbnail preview,
   specified here */
#preview-pane .preview-container {
  width: 120px;
  height: 120px;
  overflow: hidden;
}

</style>
</body>
</html>

lentics/templates/dsk.html
{% extends "base.html" %}
{% block content %}
        <h1>
            DSK
        </h1>
        <p style="text-align: justify;">
            Método para conteo de k-mers que optimiza el uso de la memoria RAM por medio de la partición de lecturas en conjuntos pequeños los cuales son guardados en disco y cargados a memoria en pequeñas cantidades. Este algoritmo se divide en 3 pasos: el primero calcula el número de k-mers, el número de iteraciones para recorrer los k-mers y el número de particiones para guardar en disco. En el segundo paso se recorren todos los k-mers y por medio de una función hash se distribuye una parte de los k-mers en las particiones. El tercer paso consiste en cargar en una tabla hash los k-mers de cada partición e irlos contando, ocupando en memoria únicamente una partición a la vez. Finalmente se repiten los 3 pasos hasta que se hayan insertado todos los k-mers.
        </p>
        <a href="http://bioinformatics.oxfordjournals.org/content/29/5/652.long" target="_blank">Publicación</a><br>
        <a href="http://minia.genouest.org/dsk/" target="_blank">Código Fuente</a>
        <hr>
        <div class="row" style="text-align:center;">
            <div class="col-sm-3"></div>
            <div class="col-sm-6">
                <form id='form' action="/run/dsk/" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_file">Archivo de k-mers:</label>
                        <select class="form-control" id="id_file" name="file"  required>
                            <option value="">seleccione un archivo</option>
                            {% for f in fileList %}
                                <option value='{{f.id}}'>{{f.fileUpload.name}}</option>
                            {% endfor %}
                        </select>* seleccione un archivo subido previamente<br><br>
                        <label for="id_k" data-toggle="tooltip" title="max: 63">Tamaño de los k-mers (valor entre 1 y 63):</label>
                        <input type="number" class="form-control" name="k" id="id_k" min="1" max="63" ><br>
                        <label for="id_minAb">Abundancia mínima:</label>
                        <input type="number" class="form-control" name="minAb" id="id_minAb" min="1" max="2147483647">
                        <p style="text-align: justify; ">
                        * Mediante este campo el usuario indica que los k-mers que tengan un conteo inferior a este valor deben ser eliminados.
                         </p>
                        <label for="id_maxAb">Abundancia máxima:</label>
                        <input type="number" class="form-control" name="maxAb" id="id_MaxAb" min="1" max="9223372036854775807"><p style="text-align: justify; ">
                        * Mediante este campo el usuario indica que los k-mers que tengan un conteo superior a este valor deben ser eliminados.
                         </p>
                    </div>
                    <button type="submit" class="btn btn-default">Enviar</button>
                </form>
            </div>
            <div class="col-sm-3"></div>
        </div>
            
        </div>

{% endblock %}

lentics/templates/error.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">

    </div>
    <div class="col-sm-6">
        <div class="alert alert-danger">
            Error:<br><br>
            {{error}}
        </div>
    </div>
    <div class="col-sm-3">

    </div>
</div>

{% endblock %}

lentics/templates/fileupload.html
{% extends "base.html" %}
{% block content %}
<h1>
    Subir archivo
</h1>
<form action="/files/submit/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_description"><h4>Descripción:</h4></label>
        <input class="form-control" id="id_description" name="description" type="text">
    </div>
    <div class="form-group">
        <label for="id_fileUploaded"><h4>Archivo:</h4></label>
        <input class="form-control" id="id_fileUploaded" name="file" type="file">
    </div>
    <button type="submit" class="btn btn-default">Subir</button>
</form>
{% endblock %}

lentics/templates/kanalyze.html
{% extends "base.html" %}
{% block content %}
<h1>
    KAnalyze
</h1>
<p style="text-align: justify;">
    Este algoritmo divide las secuencias en subconjuntos para cagarlos a memoria por partes pequeñas, lo cual permite un consumo mucho menor de memoria. Este método se divide en dos pasos: división (Split) y unión (Merge). El primer paso se encarga de tomar los k-mers y los carga en memoria (en un array) hasta que esté llena, luego el array es ordenado, se cuentan los k-mers y se escriben en disco. El segundo paso lee los archivos de conteo y los carga a memoria con un buffer para no ocupar toda la memoria disponible y los va uniendo en el archivo final de conteo, el cual queda ordenado y en disco.
</p>

<a href="http://bioinformatics.oxfordjournals.org/cgi/pmidlookup?view=long&pmid=24642064" target="_blank">Publicación</a><br>
<a href="https://sourceforge.net/p/kanalyze/code/ci/master/tree/" target="_blank">Código Fuente</a>
<hr>
<div class="row" style="text-align:center;">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
        <form id='form' action="/run/kanalyze/" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_file">Archivo de k-mers:</label>
                <select class="form-control" id="id_file" name="file" required>
                    <option value="">seleccione un archivo</option>
                    {% for f in fileList %}
                        <option value='{{f.id}}'>{{f.fileUpload.name}}</option>
                    {% endfor %}
                </select>* seleccione un archivo subido previamente<br><br>

                <label for="id_formato">Formato de entrada:</label>
                <select class="form-control" id="id_formato" name="formato" required>
                    <option value="">seleccione un formato de archivo</option>
                    <option value='0'>Raw</option>
                    <option value='1'>Fasta</option>
                    <option value='2'>Fastq</option>
                    <option value='3'>Fastagz</option>
                    <option value='4'>Fastqgz</option>
                </select><br>

                <label for="id_k" data-toggle="tooltip" title="max: 31">Tamaño de los k-mers (valor entre 1 y 31):</label>
                <input type="number" class="form-control" name="k" id="id_k" min="1" max="31" ><br>

                <label for="id_reverse">Complemento inverso:</label>
                <select class="form-control" id="id_reverse" name="reverse" required>
                    <option value="">seleccione tipo de complemento</option>
                    <option value='0'>Duplicado</option>
                    <option value='1'>Sencillo</option>
                    <option value='2'>Canónico</option>
                </select>
                <p style="text-align: justify; ">
                * <strong>Sencillo</strong>: lee los k-mers en un solo sentido.<br>
                * <strong>Duplicate</strong>: lee los k-mers en ambos sentidos.<br>
                * <strong>Canónico</strong>: lee los k-mer en ambos sentidos con complemento inverso.
                </p>
            </div>
            <button type="submit" class="btn btn-default">Enviar</button>
        </form>
    </div>
    <div class="col-sm-3"></div>
</div>
{% endblock %}

lentics/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
        <form role="form" action="/login/auth/" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Correo electrónico</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="Enter email">
            </div>
            <div class="form-group">
                <label for="password">Contraseña</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Acceder</button>
        </form>
        <div class="row">
            <p class="text-muted">¿no posee una cuenta?: <a href="/register/">Registrarse</a></p>
        </div>
    </div>
    <div class="col-sm-4"></div>
</div>
{% endblock %}

lentics/templates/proccess_error.html
{% extends "base.html" %}
{% block content %}
<h1>Proceso terminado con errores</h1>
<p>Este proceso fue ejecutado, pero finalizó con errores de tiempo de ejecución. Acontinuación se muestra la información pertinente del proceso y el error.</p><br>
<h4 style="font-weight: bold;">Comando:</h4>
	<pre>{{p.comando}}</pre>
<hr>
<h4 style="font-weight: bold;">Errores y advertencias</h4>
<pre>{% if "" == p.std_err %}El comando no devolvió errores o advertencias
{% else %}
	{{p.std_err}}
{% endif %}</pre>
{% endblock %}

lentics/templates/processes.html
{% extends "base.html" %}
{% block content %}
<h1>
    Lista de procesos finalizados
</h1>
A continuacion se listan los procesos que ha corrido en el sistema
<table class="table">
<thead>
    <tr>
        <th>ID</th>
        <th>Contador</th>
        <th>Estado</th>
        <th>Inicio</th>
        <th>Final</th>
        <th>Ver</th>
    </tr>
</thead>
<tbody>
    {% for p in process_list %}
    <tr
        {% if "Terminado exitosamente" == p.get_estado %}
            style="background-color: #7cde7c;"
        {% elif "Terminado con errores" == p.get_estado %}
            style="background-color: #ff8d00;"
        {% endif %}
    >
        <td>{{p.pk}}</td>
        <td>{{p.contador}}</td>
        <td>{{p.get_estado}}</td>
        <td>{{p.inicio}}</td>
        <td>{{p.fin}}</td>
        <td>{% if "Ejecutandose" == p.get_estado or "En espera" == p.get_estado %}
            {% elif "Terminado con errores" == p.get_estado %}
            <a href="/process/error/{{p.id}}/">Ver</a>
            {% else %}
            <a href="/process/show/{{p.id}}/">Ver</a>
            {% endif %}
    </tr>
    {% endfor %}
</tbody>
{% endblock %}

lentics/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <h2>Registro</h2><br>
            <form action="/register/" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_email">Correo electrónico:</label>
                    <input class="form-control" id="id_email" maxlength="75" name="email" type="email">
                </div>
                <div class="form-group">
                    <label for="id_firstName">Nombres:</label>
                    <input class="form-control" id="id_firstName" maxlength="30" name="firstName" type="text">
                </div>
                <div class="form-group">
                    <label for="id_lastName">Apellidos:</label>
                    <input class="form-control" id="id_lastName" maxlength="30" name="lastName" type="text">
                </div>
                <div class="form-group">
                    <label for="id_password1">Contraseña:</label>
                    <input class="form-control" id="id_password1" name="password1" type="password">
                </div>
                <div class="form-group">
                    <label for="id_password2">Repetir contraseña:</label>
                    <input class="form-control" id="id_password2" name="password2" type="password">
                </div>
                <button type="submit" class="btn btn-default">Registrarse</button>
            </form>
        </div>
        <div class="col-sm-3"> </div>
    </div>
    {% endblock %}

lentics/templates/tutorial.html
{% extends "base.html" %}
{% block content %}
aqui va un tutorial
{% endblock %}